import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      style={
        {
          "--font-geist-sans":
            'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
          "--font-geist-mono":
            '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
        } as React.CSSProperties
      }
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
